# Generated by Django 3.2.4 on 2022-08-08 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220805_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 11, 21, 56, 285781, tzinfo=utc)),
        ),
    ]
